sudo: required
language: node_js

node_js:
  - "5"

services:
  - docker

cache:
  directories:
    - node_modules

env:
  - MU_APPLICATION_GRAPH=http://mu.semte.ch/application

install:
  - npm install
  - npm install -g codeclimate-test-reporter codecov

script:
  - docker run -it --rm -v $PWD/node_modules:/app/node_modules -v $PWD/package.json:/app/package.json -v $PWD/.babelrc:/app/.babelrc -v $PWD/src/construct.js:/app/src/construct.js -v $PWD/test:/app/test -e NODE_ENV=test semtech/mu-export-template npm run lint
  - docker run -it --rm -v $PWD/node_modules:/app/node_modules -v $PWD/package.json:/app/package.json -v $PWD/.babelrc:/app/.babelrc -v $PWD/src/construct.js:/app/src/construct.js -v $PWD/test:/app/test -v $PWD/coverage:/app/coverage -e NODE_ENV=test semtech/mu-export-template npm run test:cov

after_script:
  - sed 's/\/app\///' coverage/lcov.info | codeclimate-test-reporter
  - codecov
